-- CreateTable
CREATE TABLE "ente" (
    "id" SERIAL NOT NULL,
    "alt" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateddAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ente_pkey" PRIMARY KEY ("id")
);
