export const GLOBAL_CONFIG = {
  KEYCLOAK_END_SESSION: process.env.NEXT_PUBLIC_KEYCLOAK_END_SESSION,
  SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  KEYCLOAK_CLIENT_ID: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID,
  KEYCLOAK_ISSUER: process.env.NEXT_PUBLIC_KEYCLOAK_ISSUER,
  KEYCLOAK_REFRESH_TOKEN: process.env.NEXT_PUBLIC_KEYCLOAK_REFRESH_TOKEN,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_KEYCLOAK_URL_PROVIDER: process.env.NEXTAUTH_KEYCLOAK_URL_PROVIDER,
};
